br1sk/brisk

Brisk.xcodeproj/project.pbxproj

Otherwise, CocoaPods complains with the following errors:
> The `Brisk{Tests} [{Debug,Release}]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-Brisk/Pods-Brisk.debug.xcconfig'. This can lead to problems with the CocoaPods installation

Don't override default settings for ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES

---

Brisk/Resources/Base.lproj/Main.storyboard

If you download the `0.1.0` release and run the app, the text views aren't responsive.
Confirmed that `NSTextViewDelegate` methods **are** getting called, but views were not updating.
Seems to be an issue with layout constraints. This isn't a perfect fix, but it works. Text views are now responsive.
Issues:
The "description" text view doesn't resize it's height like the others when resizing the window. Not sure how to fix this.
Fixes #30.

Fix storyboard constraints so textViews are responsive, fixes #30

---

Brisk/Resources/Assets.xcassets/StatusItemIcon.imageset/Contents.json

Without this setting, the icon renders as black even in dark mode.

Update menu bar icon to render as template

---

Brisk/Resources/Base.lproj/Main.storyboard

At some point during development I added command + enter as a keyboard
shortcut to logout. This makes the button blue and looks like pressing
enter will do it. We don't need to make it this easy to logout.
Closes https://github.com/br1sk/brisk/issues/26

Remove logout button keyboard shortcut

---

Brisk/Controllers/RadarViewController.swift
Brisk/Extensions/Radar+Serialization.swift
BriskTests/RadarSerializationTests.swift
Podfile.lock

Previously the area field on Radar was only used for iOS. Now it's used
for multiple products, yet the items with the same names across products
don't particularly have the same IDs. This updates the area picker to be
populated by the areas per product, and cleared when switching to a
product with no areas.

Fix areas by product

---

Brisk/Controllers/RadarViewController.swift

Before more than just the iOS product support areas, Brisk actually had
a bug where it was sending the last selected iOS area regardless of
product. This also meant it was saving the wrong area when saving the
json file.
Once we changed to having areas for some products, and not others, this
caused 2 new bugs.
- Validation would never pass for products without areas
This was caused because the areaPopUp was validated, but its title was
an empty string. It has now been removed from the validation list
(there's also a possible fix for this where pop up buttons are validated
by having a title, or being disabled)
- Brisk would crash when saving a radar for a product that didn't
support areas.
This was because we were always assuming the areaPopUp would have a
value, but it wouldn't for most …

Fix some area related bugs

---

Brisk/AppDelegate.swift

After launching brisk with the dock icon active, if you attempted to
click the menu bar immediately after it was launched, it would not be
interactive. To fix this you had to focus a different app, and then
refocus brisk.
This seemed to be caused by the setActivationPolicy call being in
applicationDidFinishLaunching rather than
applicationWillFinishLaunching. Moving this initialization there seems to
fix this issue.
https://stackoverflow.com/questions/33345686/cocoa-application-menu-bar-not-clickable

Fix non-responsive menu bar on first launch

---

Brisk/AppDelegate.swift

Before brisk had the option of showing a dock icon, when launching it
into a menu bar icon, we wouldn't open a new window. This was because
menu bar apps should ideally be low key until you need them.
Once we added the preference for showing a dock icon we never rethought
this.
This updates the logic to open a new untitled window if you're showing
the dock icon.
Things to note about this API:
1. It's called before `didFinishLaunching`
2. We're not registering the defaults before accessing them
3. This should only matter if you don't have windows to reopen

Open an untitled window on launch with dock icon

---

Brisk/Resources/Base.lproj/Main.storyboard
CHANGELOG.md

Previously if you had an attachment that had a long name it would
overlap the submit button. Now it truncates in the middle.

Middle truncate long attachment names

---

Brisk/Resources/Base.lproj/Main.storyboard
CHANGELOG.md

This allowed users to change a lot of formatting in text views that
didn't end up being represented in the final radar. To reduce confusion
on that it's now just disabled.

Remove Ruler support from text views

---

Brisk/Resources/Info.plist
CHANGELOG.md

Not sure why this was necessary, it seems like it isn't anymore (if it
ever was).

Remove ATS exceptions

---

Brisk/Views/TextView.swift
CHANGELOG.md

Previously this would insert tabs into the textview, but this probably
makes more sense to navigate between fields. This flips the behavior of
Ctrl + tab switching between fields to make that actually insert a tab.

Make TextView tab and backtab switch between fields

---

Brisk.xcodeproj/project.pbxproj
Brisk/AppDelegate.swift
Brisk/Controllers/FileDuplicateViewController.swift
Brisk/Extensions/Attachment+Serialization.swift
Brisk/Extensions/Data+Extension.swift
Brisk/Extensions/Dictionary+Extension.swift
Brisk/Extensions/NSDocumentController+Extension.swift
Brisk/Extensions/NSProgressIndicator+Extension.swift
Brisk/Extensions/Radar+OpenRadar.swift
Brisk/Extensions/Radar+Serialization.swift
Brisk/Extensions/String+Extension.swift
Brisk/Models/OpenRadar.swift
Brisk/Models/RadarDocument.swift
Brisk/Resources/Base.lproj/Main.storyboard
BriskTests/DictionaryExtensionTests.swift
BriskTests/OpenRadarTests.swift
BriskTests/RadarIDParsingTests.swift
BriskTests/RadarSerializationTests.swift
BriskTests/Resources/openradar.json
BriskTests/Resources/openradarstrings.json
BriskTests/StringExtensionTests.swift
CHANGELOG.md
Podfile.lock

This adds a new window for duping a radar. It takes the ID of a radar,
searches OpenRadar for the details about it, and then fills the normal
UI with the values from it.
The complex part of this is what we put into what fields in the UI from
OpenRadar. The OpenRadar API just returns one big blog of summary data
(exactly how radarweb displays it), so instead of parsing that, we're
just filling the description with that.
It ends up looking a little weird since we're only filling 1 of the 5
text views, but it shouldn't be a big deal. Also OpenRadar doesn't vend
the `area` field sent to radar, so to default to something we just
choose "other".

Add logic for duping radar

---

Brisk/AppDelegate.swift
Brisk/Controllers/FileDuplicateViewController.swift
Brisk/Resources/Base.lproj/Main.storyboard
Brisk/Resources/Info.plist
CHANGELOG.md

This makes the app responsive to rdar:// URLs. rdar://12345 will open
the app, search OpenRadar for radar 12345, and will display its
contents if available on OpenRadar. The radar can then easily be duped.
Fixes https://github.com/br1sk/brisk/issues/77

Follow rdar:// URLs

---

Brisk/AppDelegate.swift
CHANGELOG.md

Previously you could open a `.brisk` file multiple times. Now if that
file is already open, we focus the window(s) instead.

Focus already open document on reopen

---

Brisk/Resources/Base.lproj/Main.storyboard
CHANGELOG.md

For now this can be used as the last icon for preferences. In the future
I think we should change to a more Mail.app like approach where we have
a single accounts tab that has Apple Radar, Open Radar, and maybe things
like the Swift JIRA and Twitter. In that case we'll only have a single
icon.

Use single user icon for open radar preferences

---

.swiftlint.yml
Brisk.xcodeproj/project.pbxproj
Brisk/Controllers/RadarViewController.swift
Brisk/Extensions/Radar+OpenRadar.swift
Brisk/Resources/Base.lproj/Main.storyboard
Brisk/Views/PlaceholderTextView.swift
Brisk/Views/TextView.swift
BriskTests/OpenRadarTests.swift
CHANGELOG.md

This mirrors the required / optional behavior from radarweb. I haven't
checked the "API" to see if any other fields are accepted as empty, even
though they are required in the radar UI, but I think matching that
behavior makes sense.

Make configuration and notes fields optional

---

Brisk/Controllers/RadarViewController.swift
CHANGELOG.md

Right now whenever you type anything in any field we wipe out the title
field. We should only update the title when the title text is non-empty.
I would set the document's title to nil when you delete it, but if you
do that you end up with a document named "Untitled -1" which then syncs
with the window's title bar and seems crazy.

Only update title with valid title text

---

Brisk/Controllers/RadarViewController.swift
Brisk/Models/RadarDocument.swift
CHANGELOG.md

When restoring a Radar that doesn't have an associated URL, mark the
document as dirty.

Register file change for duplicates

---

Brisk/Controllers/RadarViewController.swift
Brisk/Resources/Base.lproj/Main.storyboard
CHANGELOG.md

This turns what was previously the "Add Attachment" button into a toggle
attachment button where it either adds or removes the attachment based
on if you already have one.

Add ability to remove attachment

---

Brisk/Controllers/RadarViewController.swift
CHANGELOG.md

Previously if you started to dup a radar, we filled in all the fields in
the window, which sets the document change count to edited. Then if you
closed the window, you would be prompted to save the document. In this
case where you haven't edited anything, the document will be immediately
closable and you will only be prompted to save the document if you make
changes to it.

Reset change count when loading radar

---

Brisk/Controllers/RadarViewController.swift
CHANGELOG.md

Previously if you were duping a radar, when the window was populated the
title was out of sync with the content. Then the first time you
interacted with the fields, the title would sync. Now it syncs
immediately.

Update the title when restoring a radar

---

Brisk/Controllers/RadarViewController.swift
CHANGELOG.md

Below this we cleared all changes because of the newer change behavior,
so this isn't necessary.

Remove unnecessary change count change

---

Brisk/Controllers/RadarViewController.swift
Brisk/Resources/Base.lproj/Main.storyboard
CHANGELOG.md

This adds a checkbox in each window for whether or not the current radar
should be cross posted to open radar. This is useful for when you want
to keep a radar private, or you just don't want to cross post a
duplicate to open radar.
This won't scale if we want to allow:
- only posting to openradar (perhaps if you just want to post something
you've already posted to apple radar)
- support for more services
But in the meantime I think having a way to customize this is important
so it's worth adding this way for now.

Add checkbox for crossposting to open radar

---

Brisk.xcodeproj/project.pbxproj
Brisk/Controllers/RadarViewController.swift
Brisk/Resources/Base.lproj/Main.storyboard
Brisk/Views/AttachmentDroppableView.swift
CHANGELOG.md

This allows you to drag and drop a single attachment onto the bottom of
the new radar UI
This supersedes https://github.com/br1sk/brisk/pull/102 and fixes https://github.com/br1sk/brisk/issues/35

Add attachment drag and drop support

---

Brisk/Controllers/RadarViewController.swift
CHANGELOG.md

This defaults the checkbox for crossposting to open radar to false when
you are:
1. Explicitly filing a duplicate
2. Opening a `*.brisk` file
You can of course check this checkbox if you actually want to cross post
it.
Fixes https://github.com/br1sk/brisk/issues/106

Default posting to open radar to false when duping

---

Brisk/Resources/Base.lproj/Main.storyboard
CHANGELOG.md

The position of the version and configuration fields wasn't really set
before. This only appeared in the runtime issues tab so I hadn't noticed
it.

Fix silently ambiguous layout

---

Brisk/Resources/Base.lproj/Main.storyboard

This removes the final constraint to the text views inside the stack
view. It seems like AppKit doesn't like things being constrained inside
here, or I'm just missing what's wrong with it, so hopefully this helps
with some layout issues.

Remove constraint from text view

---

Brisk/Controllers/AuthenticationViewController.swift
CHANGELOG.md

Fixes #133 
Turns out that when using my text expander app for the email it adds a space at the end which causes authentication to fail.

Remove whitespace from appleIDTextField

---

Brisk/Resources/Base.lproj/Main.storyboard
CHANGELOG.md

Previously the initial height of the preferences window was unbounded,
and took a system default.

Fix preferences window initial height
